/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import bd.ConexionBd;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Pelicula;
/**
 *
 * @author GOLDEN GAMERS
 */
public class PanelTrabajo extends javax.swing.JFrame {
    /**
     * Creates new form PanelTrabajo
    */
    ConexionBd c = new ConexionBd();
    Connection cn = c.getConectarDB();
    
    
    public PanelTrabajo() {
        initComponents();
        listar();
    }
    
    public void listar (){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("IdPelicula");
        modelo.addColumn("Titulo");
        modelo.addColumn("Director");
        modelo.addColumn("Anio");
        modelo.addColumn("Duracion");
        modelo.addColumn("Genero");
        TablaDatos.setModel(modelo);
        
        String sql = "SELECT * FROM movie" ;
        
        String datos[] = new String [6];
        
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                datos[0]= rs.getString(1);
                datos[1]= rs.getString(2);
                datos[2]= rs.getString(3);
                datos[3]= rs.getString(4);
                datos[4]= rs.getString(5);
                datos[5]= rs.getString(6);
                modelo.addRow(datos);
            }
            TablaDatos.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdPelicula = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtDirector = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        jComboBox1Genero = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButton3Listar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton3ELIMINAR = new javax.swing.JButton();
        txtEliminar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jButton3BUSCAR = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jButton3MODIFICARTITULO = new javax.swing.JButton();
        txtModificarTitulo = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton4MODIFICARDIRECTOR = new javax.swing.JButton();
        txtModificarDirector = new javax.swing.JTextField();
        jButton5MODIFICARANIO = new javax.swing.JButton();
        txtModifcarAnio = new javax.swing.JTextField();
        jButton6MODIFICARDURACION = new javax.swing.JButton();
        jButton7MODIFICARGENERO = new javax.swing.JButton();
        txtModificarDuracion = new javax.swing.JTextField();
        jComboBoxmodificargenero = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFiltrar = new javax.swing.JMenu();
        MenuFiltrar = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cine HoytsMarkPlanet");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("TITULO");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("DIRECTOR");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("ANIO");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("DURACION (MIN)");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("GENERO");

        txtIdPelicula.setEditable(false);
        txtIdPelicula.setText("AUTONUMERICO");

        txtTitulo.setToolTipText("");

        txtDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirectorActionPerformed(evt);
            }
        });

        txtAnio.setText("0");

        txtDuracion.setText("0");

        jComboBox1Genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Comedia", "Drama", "Accion", "Terror", "Fantasia" }));
        jComboBox1Genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1GeneroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdPelicula)
                            .addComponent(txtTitulo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAnio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDirector)
                            .addComponent(txtDuracion)
                            .addComponent(jComboBox1Genero, 0, 107, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jButton3Listar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3Listar.setText("LISTAR");
        jButton3Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ListarActionPerformed(evt);
            }
        });

        TablaDatos.setBorder(new javax.swing.border.MatteBorder(null));
        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaDatos.setEnabled(false);
        jScrollPane4.setViewportView(TablaDatos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3Listar)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3Listar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        jButton3ELIMINAR.setText("ELIMINAR");
        jButton3ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ELIMINARActionPerformed(evt);
            }
        });

        txtEliminar.setText("0");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("ID PELICULA");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton3ELIMINAR)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtEliminar))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3ELIMINAR)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));

        jButton3BUSCAR.setText("BUSCAR ID");
        jButton3BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3BUSCARActionPerformed(evt);
            }
        });

        jButton3MODIFICARTITULO.setText("MODIFICAR TITULO");
        jButton3MODIFICARTITULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3MODIFICARTITULOActionPerformed(evt);
            }
        });

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        jButton4MODIFICARDIRECTOR.setText("MODIFICAR DIRECTOR");
        jButton4MODIFICARDIRECTOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4MODIFICARDIRECTORActionPerformed(evt);
            }
        });

        jButton5MODIFICARANIO.setText("MODIFICAR ANIO");
        jButton5MODIFICARANIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5MODIFICARANIOActionPerformed(evt);
            }
        });

        jButton6MODIFICARDURACION.setText("MODIFICAR DURACION(MIN)");
        jButton6MODIFICARDURACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6MODIFICARDURACIONActionPerformed(evt);
            }
        });

        jButton7MODIFICARGENERO.setText("MODIFICAR GENERO");
        jButton7MODIFICARGENERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7MODIFICARGENEROActionPerformed(evt);
            }
        });

        jComboBoxmodificargenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Comedia", "Drama", "Accion", "Terror", "Fantasia" }));
        jComboBoxmodificargenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxmodificargeneroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3BUSCAR)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtModificarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton4MODIFICARDIRECTOR)
                                        .addComponent(jButton5MODIFICARANIO)
                                        .addComponent(jButton6MODIFICARDURACION))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBoxmodificargenero, 0, 107, Short.MAX_VALUE)
                                        .addComponent(txtModificarDirector)
                                        .addComponent(txtModifcarAnio)
                                        .addComponent(txtModificarDuracion)))
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton7MODIFICARGENERO)
                                    .addComponent(jButton3MODIFICARTITULO))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3BUSCAR)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3MODIFICARTITULO)
                    .addComponent(txtModificarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4MODIFICARDIRECTOR)
                    .addComponent(txtModificarDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5MODIFICARANIO)
                    .addComponent(txtModifcarAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6MODIFICARDURACION)
                    .addComponent(txtModificarDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7MODIFICARGENERO)
                    .addComponent(jComboBoxmodificargenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuFiltrar.setText("Menu");
        jMenuFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFiltrarActionPerformed(evt);
            }
        });

        MenuFiltrar.setText("Filtrar");
        MenuFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFiltrarActionPerformed(evt);
            }
        });
        jMenuFiltrar.add(MenuFiltrar);

        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        jMenuFiltrar.add(MenuSalir);

        jMenuBar1.add(jMenuFiltrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Pelicula pelicula = new Pelicula(HEIGHT,txtTitulo.getText() , txtDirector.getText(), Integer.parseInt(txtAnio.getText()), Integer.parseInt(txtDuracion.getText()), (String) jComboBox1Genero.getSelectedItem());
        
        int indice = jComboBox1Genero.getSelectedIndex();
            if (indice == 0) {
                JOptionPane.showMessageDialog(null, "HAY CAMPOS SIN DATOS O VALORES INCORRECTOS, DEBES LLENARLOS", "Error", JOptionPane.ERROR_MESSAGE); 
                jTextArea1.setText("DEBES SELECCIONAR UN GENERO PARA PORDER AGREGAR");
            } else {
                c.agregar(pelicula,jTextArea1);
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtIdPelicula.setText("AUTONUMERICO");
        txtTitulo.setText("");
        txtDirector.setText("");
        txtAnio.setText("0");
        txtDuracion.setText("0");
        txtEliminar.setText("0");
        txtModifcarAnio.setText("");
        txtModificarDirector.setText("");
        txtModificarDuracion.setText("");
        txtModificarTitulo.setText("");   
        txtBuscar.setText("");
        jTextArea1.setText("");
        jTextArea2.setText("");
        jTextArea3.setText("");
        jComboBoxmodificargenero.setSelectedIndex(0);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ListarActionPerformed
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_jButton3ListarActionPerformed

    private void jButton3BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3BUSCARActionPerformed
        // TODO add your handling code here:
        if (txtBuscar.getText().trim().isEmpty()) {
            jTextArea3.setText("CAMPO VACIO, DEBES LLENARLO PARA BUSCAR");
        }else{
            try {
                int idPeliculaBuscar = Integer.parseInt(txtBuscar.getText());
                Pelicula peliculaEncontrada = c.buscar(idPeliculaBuscar);
                if (peliculaEncontrada != null) {
                    String mostrarDatos = 
                        "ID: " + peliculaEncontrada.getIdPelicula() + "\n" +
                        "Titulo: " + peliculaEncontrada.getTitulo() + "\n" +
                        "Director: " + peliculaEncontrada.getDirector() + "\n" +
                        "Anio: " + peliculaEncontrada.getAnio() + "\n" +
                        "Duracion: " + peliculaEncontrada.getDuracion() + " minutos\n" +
                        "Genero: " + peliculaEncontrada.getGenero();
                        jTextArea3.setText(mostrarDatos);
                }else{
                    jTextArea3.setText("Pelicula no encontrada");
                    }
                } catch (NumberFormatException e) {
                    jTextArea3.setText("ID INVALIDO: " + txtBuscar.getText() + ". Debe ser un numero entero.");
                }
            }
    }//GEN-LAST:event_jButton3BUSCARActionPerformed

    private void jButton3ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ELIMINARActionPerformed
        // TODO add your handling code here:
        //eliminar
        if (txtEliminar.getText().trim().isEmpty()) {
            jTextArea2.setText("CAMPO VACIO, DEBES LLENARLO PARA MODIFICAR");
        }else{
         //c.eliminar(txtEliminar.getText());
           c.eliminar(txtEliminar.getText(),jTextArea2);
        }    
    }//GEN-LAST:event_jButton3ELIMINARActionPerformed

    private void jButton3MODIFICARTITULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3MODIFICARTITULOActionPerformed
        // TODO add your handling code here:
        if (txtBuscar.getText().trim().isEmpty()) {
            jTextArea3.setText("Debes buscar por el id de pelicula antes de intentar modificar");
        } else if (txtModificarTitulo.getText().trim().isEmpty()) {
                    jTextArea3.setText("CAMPO VACIO, DEBES LLENARLO PARA MODIFICAR");
        } else {
            int idPeliculaBuscar = Integer.parseInt(txtBuscar.getText());
            Pelicula peliculaExistente = c.buscar(idPeliculaBuscar);
            if (peliculaExistente == null) {
                jTextArea3.setText("No se puede modificar. La pelicula con ID " + idPeliculaBuscar + " no existe.");
            } else {
                c.modificarTitulo(idPeliculaBuscar, txtModificarTitulo.getText());
        
                Pelicula peliculaModificada = c.buscar(idPeliculaBuscar);
                if (peliculaModificada != null) {
                    String mostrarDatos = 
                            "ID: " + peliculaModificada.getIdPelicula() + "\n" +
                            "Titulo: " + peliculaModificada.getTitulo() + "\n" +
                            "Director: " + peliculaModificada.getDirector() + "\n" +
                            "Anio: " + peliculaModificada.getAnio() + "\n" +
                            "Duracion: " + peliculaModificada.getDuracion() + " minutos\n" +
                            "Genero: " + peliculaModificada.getGenero();
                    jTextArea3.setText(mostrarDatos);
                }
            }
        }

    }//GEN-LAST:event_jButton3MODIFICARTITULOActionPerformed

    private void jButton4MODIFICARDIRECTORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4MODIFICARDIRECTORActionPerformed
        // TODO add your handling code here:
        if (txtBuscar.getText().trim().isEmpty()) {
            jTextArea3.setText("Debes buscar por el id de pelicula antes de intentar modificar");
        } else if (txtModificarDirector.getText().trim().isEmpty()) {
            jTextArea3.setText("CAMPO VACIO, DEBES LLENARLO PARA MODIFICAR");
        } else {
            int idPeliculaBuscar = Integer.parseInt(txtBuscar.getText());
            
            Pelicula peliculaExistente = c.buscar(idPeliculaBuscar);
            if (peliculaExistente == null) {
                jTextArea3.setText("No se puede modificar. La pelIcula con ID " + idPeliculaBuscar + " no existe.");
            } else {
                c.modificarDirector(idPeliculaBuscar, txtModificarDirector.getText());

                Pelicula peliculaModificada = c.buscar(idPeliculaBuscar);
                if (peliculaModificada != null) {
                    String mostrarDatos = 
                            "ID: " + peliculaModificada.getIdPelicula() + "\n" +
                            "Titulo: " + peliculaModificada.getTitulo() + "\n" +
                            "Director: " + peliculaModificada.getDirector() + "\n" +
                            "Anio: " + peliculaModificada.getAnio() + "\n" +
                            "Duracion: " + peliculaModificada.getDuracion() + " minutos\n" +
                            "Genero: " + peliculaModificada.getGenero();
                    jTextArea3.setText(mostrarDatos);
                }
            }
        }
    }//GEN-LAST:event_jButton4MODIFICARDIRECTORActionPerformed

    private void jButton5MODIFICARANIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5MODIFICARANIOActionPerformed
        // TODO add your handling code here:
        if (txtBuscar.getText().trim().isEmpty()) {
            jTextArea3.setText("Debes buscar por el id de pelicula antes de intentar modificar");
        } else if (txtModifcarAnio.getText().trim().isEmpty()) {
            jTextArea3.setText("CAMPO VACIO, DEBES LLENARLO PARA MODIFICAR");
        } else {
            int idPeliculaBuscar = Integer.parseInt(txtBuscar.getText());
            
            Pelicula peliculaExistente = c.buscar(idPeliculaBuscar);
            if (peliculaExistente == null) {
                jTextArea3.setText("No se puede modificar. La pelicula con ID " + idPeliculaBuscar + " no existe.");
            } else {
                try {
                    int nuevoAnio = Integer.parseInt(txtModifcarAnio.getText());
                    c.modificarAnio(idPeliculaBuscar, nuevoAnio);

                    Pelicula peliculaModificada = c.buscar(idPeliculaBuscar);
                    if (peliculaModificada != null) {
                        String mostrarDatos =
                                "ID: " + peliculaModificada.getIdPelicula() + "\n" +
                                "Titulo: " + peliculaModificada.getTitulo() + "\n" +
                                "Director: " + peliculaModificada.getDirector() + "\n" +
                                "Anio: " + peliculaModificada.getAnio() + "\n" +
                                "Duracion: " + peliculaModificada.getDuracion() + " minutos\n" +
                                "Genero: " + peliculaModificada.getGenero();
                        jTextArea3.setText(mostrarDatos);
                    }
                } catch (NumberFormatException e) { 
                    jTextArea3.setText("Debes ingresar un valor numerico para el campo año.");
                }
            }
        }

    }//GEN-LAST:event_jButton5MODIFICARANIOActionPerformed

    private void jButton6MODIFICARDURACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6MODIFICARDURACIONActionPerformed
        // TODO add your handling code here:
        if (txtBuscar.getText().trim().isEmpty()) {
            jTextArea3.setText("Debes buscar por el id de pelicula antes de intentar modificar");
        } else if (txtModificarDuracion.getText().trim().isEmpty()) {
            jTextArea3.setText("CAMPO VACIO, DEBES LLENARLO PARA MODIFICAR");
        } else {
            int idPeliculaBuscar = Integer.parseInt(txtBuscar.getText());

            Pelicula peliculaExistente = c.buscar(idPeliculaBuscar);
            if (peliculaExistente == null) {
                jTextArea3.setText("No se puede modificar. La película con ID " + idPeliculaBuscar + " no existe.");
            } else {
                try {
                    int nuevaDuracion = Integer.parseInt(txtModificarDuracion.getText());
                    c.modificarDuracion(idPeliculaBuscar, nuevaDuracion);

                    Pelicula peliculaModificada = c.buscar(idPeliculaBuscar);
                    if (peliculaModificada != null) {
                        String mostrarDatos =
                                "ID: " + peliculaModificada.getIdPelicula() + "\n" +
                                "Titulo: " + peliculaModificada.getTitulo() + "\n" +
                                "Director: " + peliculaModificada.getDirector() + "\n" +
                                "Anio: " + peliculaModificada.getAnio() + "\n" +
                                "Duracion: " + peliculaModificada.getDuracion() + " minutos\n" +
                                "Genero: " + peliculaModificada.getGenero();
                        jTextArea3.setText(mostrarDatos);
                    }
                } catch (NumberFormatException e) {
                    jTextArea3.setText("Debes ingresar un valor numerico para el campo duracion.");
                }
            }
        }
    }//GEN-LAST:event_jButton6MODIFICARDURACIONActionPerformed

    private void jButton7MODIFICARGENEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7MODIFICARGENEROActionPerformed
        // TODO add your handling code here:
        if (txtBuscar.getText().trim().isEmpty()) {
            jTextArea3.setText("Debes buscar por el id de pelicula antes de intentar modificar");
        } else {
            int indice1 = jComboBoxmodificargenero.getSelectedIndex();
    
            if (indice1 == 0) {
                jTextArea3.setText("DEBES SELECCIONAR UN GENERO PARA MODIFICAR");
            } else {
                int idPeliculaBuscar = Integer.parseInt(txtBuscar.getText());
                
                Pelicula peliculaExistente = c.buscar(idPeliculaBuscar);
                if (peliculaExistente == null) {
                    jTextArea3.setText("No se puede modificar. La pelicula con ID " + idPeliculaBuscar + " no existe.");
                } else {
                    c.modificarGenero(idPeliculaBuscar, (String) jComboBoxmodificargenero.getSelectedItem());

                    Pelicula peliculaModificada = c.buscar(idPeliculaBuscar);
                    if (peliculaModificada != null) {
                        String mostrarDatos =
                                "ID: " + peliculaModificada.getIdPelicula() + "\n" +
                                "Titulo: " + peliculaModificada.getTitulo() + "\n" +
                                "Director: " + peliculaModificada.getDirector() + "\n" +
                                "Anio: " + peliculaModificada.getAnio() + "\n" +
                                "Duracion: " + peliculaModificada.getDuracion() + " minutos\n" +
                                "Genero: " + peliculaModificada.getGenero();
                        jTextArea3.setText(mostrarDatos);
                    }
                }
            }
        }

    }//GEN-LAST:event_jButton7MODIFICARGENEROActionPerformed

    private void jMenuFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuFiltrarActionPerformed

    private void jComboBox1GeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1GeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1GeneroActionPerformed

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        Salir salir = new Salir(this, true); 
        salir.setVisible(true);
    }//GEN-LAST:event_MenuSalirActionPerformed

    private void MenuFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFiltrarActionPerformed
        // TODO add your handling code here:
        Filtrar filtrar = new Filtrar(this, true); 
        filtrar.setVisible(true);
    }//GEN-LAST:event_MenuFiltrarActionPerformed

    private void jComboBoxmodificargeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxmodificargeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxmodificargeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelTrabajo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuFiltrar;
    private javax.swing.JMenuItem MenuSalir;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3BUSCAR;
    private javax.swing.JButton jButton3ELIMINAR;
    public javax.swing.JButton jButton3Listar;
    private javax.swing.JButton jButton3MODIFICARTITULO;
    private javax.swing.JButton jButton4MODIFICARDIRECTOR;
    private javax.swing.JButton jButton5MODIFICARANIO;
    private javax.swing.JButton jButton6MODIFICARDURACION;
    private javax.swing.JButton jButton7MODIFICARGENERO;
    private javax.swing.JComboBox<String> jComboBox1Genero;
    private javax.swing.JComboBox<String> jComboBoxmodificargenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFiltrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtEliminar;
    private javax.swing.JTextField txtIdPelicula;
    private javax.swing.JTextField txtModifcarAnio;
    private javax.swing.JTextField txtModificarDirector;
    private javax.swing.JTextField txtModificarDuracion;
    private javax.swing.JTextField txtModificarTitulo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
